apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
    env: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
        env: staging
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
    env: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
        env: staging
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
