apiVersion: v1
kind: Service
metadata:
  name: vote
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "vote"
    port: 8080
  selector:
    app: vote

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: pchico83/alumnos:vote
        name: vote