apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
spec:
  rules:
  - host: ingress1-pchico83.cloud.okteto.net
    http:
      paths:
      - backend:
          serviceName: mundo
          servicePort: 80
        path: /
  - host: ingress2-pchico83.cloud.okteto.net
    http:
      paths:
      - backend:
          serviceName: alumnos
          servicePort: 80
        path: /
  tls:
  - hosts:
    - ingress1-pchico83.cloud.okteto.net
    - ingress2-pchico83.cloud.okteto.net

---  

apiVersion: v1
kind: Service
metadata:
  name: mundo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mundo
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mundo
  labels:
    app: mundo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mundo
  template:
    metadata:
      labels:
        app: mundo
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: content
        image: alpine
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data
        command: ["sh"]
        args: ["-c", "echo Hola Mundo! > /pod-data/index.html"]
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

---

apiVersion: v1
kind: Service
metadata:
  name: alumnos
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: alumnos
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumnos
  labels:
    app: alumnos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alumnos
  template:
    metadata:
      labels:
        app: alumnos
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: content
        image: alpine
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data
        command: ["sh"]
        args: ["-c", "echo Hola Alumnos! > /pod-data/index.html"]
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
